(define (control-knowledge ck1) (:domain mais) (:problem p1)
    (:temporal-constraints
        (and
	(t-exists (?prepare_barb0p0 - (prepare_bar b0 p0)) 
		(t-exists (?loadh0b0p0 - (load h0 b0 p0)) 
		(t-exists (?unloadh0b0p1 - (unload h0 b0 p1)) 
		(t-exists (?loadh0b0p1 - (load h0 b0 p1)) 
		(t-exists (?unloadh0b0p2 - (unload h0 b0 p2)) 
		(t-exists (?loadh0b0p2 - (load h0 b0 p2)) 
		(t-exists (?unloadh0b0p3 - (unload h0 b0 p3)) 
		(t-exists (?loadh0b0p3 - (load h0 b0 p3)) 
		(t-exists (?unloadh0b0p4 - (unload h0 b0 p4)) 
		(t-exists (?loadh0b0p4 - (load h0 b0 p4)) 
		(t-exists (?unloadh0b0p5 - (unload h0 b0 p5)) 
		(t-exists (?loadh0b0p5 - (load h0 b0 p5)) 
		(t-exists (?unloadh0b0p6 - (unload h0 b0 p6)) 
		(t-exists (?finish_barb0p6 - (finish_bar b0 p6)) 
		(and (= (- ?loadh0b0p0 ?prepare_barb0p0) 60)(>= (- ?loadh0b0p1 ?unloadh0b0p1) 10)(<= (- ?loadh0b0p1 ?unloadh0b0p1) 30)(>= (- ?loadh0b0p2 ?unloadh0b0p2) 10)(<= (- ?loadh0b0p2 ?unloadh0b0p2) 30)(>= (- ?loadh0b0p3 ?unloadh0b0p3) 10)(<= (- ?loadh0b0p3 ?unloadh0b0p3) 30)(>= (- ?loadh0b0p4 ?unloadh0b0p4) 10)(<= (- ?loadh0b0p4 ?unloadh0b0p4) 30)(>= (- ?loadh0b0p5 ?unloadh0b0p5) 10)(<= (- ?loadh0b0p5 ?unloadh0b0p5) 30)(= (- ?finish_barb0p6 ?unloadh0b0p6) 60))))))))))))))))
	(t-forall (?ms - (move_start h0 p0 p1))
	 (t-exists (?me - (move_end h0 p0 p1)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p0 p1))
	 (t-exists (?ms - (move_start h0 p0 p1)) (and (= (- ?me ?ms) 10))))	
	(t-forall (?ms - (move_start h0 p0 p2))
	 (t-exists (?me - (move_end h0 p0 p2)) (and (= (- ?me ?ms) 20))))
	(t-forall (?me - (move_end h0 p0 p2))
	 (t-exists (?ms - (move_start h0 p0 p2)) (and (= (- ?me ?ms) 20))))	
	(t-forall (?ms - (move_start h0 p0 p3))
	 (t-exists (?me - (move_end h0 p0 p3)) (and (= (- ?me ?ms) 30))))
	(t-forall (?me - (move_end h0 p0 p3))
	 (t-exists (?ms - (move_start h0 p0 p3)) (and (= (- ?me ?ms) 30))))	
	(t-forall (?ms - (move_start h0 p0 p4))
	 (t-exists (?me - (move_end h0 p0 p4)) (and (= (- ?me ?ms) 40))))
	(t-forall (?me - (move_end h0 p0 p4))
	 (t-exists (?ms - (move_start h0 p0 p4)) (and (= (- ?me ?ms) 40))))	
	(t-forall (?ms - (move_start h0 p0 p5))
	 (t-exists (?me - (move_end h0 p0 p5)) (and (= (- ?me ?ms) 50))))
	(t-forall (?me - (move_end h0 p0 p5))
	 (t-exists (?ms - (move_start h0 p0 p5)) (and (= (- ?me ?ms) 50))))	
	(t-forall (?ms - (move_start h0 p0 p6))
	 (t-exists (?me - (move_end h0 p0 p6)) (and (= (- ?me ?ms) 60))))
	(t-forall (?me - (move_end h0 p0 p6))
	 (t-exists (?ms - (move_start h0 p0 p6)) (and (= (- ?me ?ms) 60))))	
	(t-forall (?ms - (move_start h0 p1 p0))
	 (t-exists (?me - (move_end h0 p1 p0)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p1 p0))
	 (t-exists (?ms - (move_start h0 p1 p0)) (and (= (- ?me ?ms) 10))))	
	(t-forall (?ms - (move_start h0 p1 p2))
	 (t-exists (?me - (move_end h0 p1 p2)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p1 p2))
	 (t-exists (?ms - (move_start h0 p1 p2)) (and (= (- ?me ?ms) 10))))	
	(t-forall (?ms - (move_start h0 p1 p3))
	 (t-exists (?me - (move_end h0 p1 p3)) (and (= (- ?me ?ms) 20))))
	(t-forall (?me - (move_end h0 p1 p3))
	 (t-exists (?ms - (move_start h0 p1 p3)) (and (= (- ?me ?ms) 20))))	
	(t-forall (?ms - (move_start h0 p1 p4))
	 (t-exists (?me - (move_end h0 p1 p4)) (and (= (- ?me ?ms) 30))))
	(t-forall (?me - (move_end h0 p1 p4))
	 (t-exists (?ms - (move_start h0 p1 p4)) (and (= (- ?me ?ms) 30))))	
	(t-forall (?ms - (move_start h0 p1 p5))
	 (t-exists (?me - (move_end h0 p1 p5)) (and (= (- ?me ?ms) 40))))
	(t-forall (?me - (move_end h0 p1 p5))
	 (t-exists (?ms - (move_start h0 p1 p5)) (and (= (- ?me ?ms) 40))))	
	(t-forall (?ms - (move_start h0 p1 p6))
	 (t-exists (?me - (move_end h0 p1 p6)) (and (= (- ?me ?ms) 50))))
	(t-forall (?me - (move_end h0 p1 p6))
	 (t-exists (?ms - (move_start h0 p1 p6)) (and (= (- ?me ?ms) 50))))	
	(t-forall (?ms - (move_start h0 p2 p0))
	 (t-exists (?me - (move_end h0 p2 p0)) (and (= (- ?me ?ms) 20))))
	(t-forall (?me - (move_end h0 p2 p0))
	 (t-exists (?ms - (move_start h0 p2 p0)) (and (= (- ?me ?ms) 20))))	
	(t-forall (?ms - (move_start h0 p2 p1))
	 (t-exists (?me - (move_end h0 p2 p1)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p2 p1))
	 (t-exists (?ms - (move_start h0 p2 p1)) (and (= (- ?me ?ms) 10))))	
	(t-forall (?ms - (move_start h0 p2 p3))
	 (t-exists (?me - (move_end h0 p2 p3)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p2 p3))
	 (t-exists (?ms - (move_start h0 p2 p3)) (and (= (- ?me ?ms) 10))))	
	(t-forall (?ms - (move_start h0 p2 p4))
	 (t-exists (?me - (move_end h0 p2 p4)) (and (= (- ?me ?ms) 20))))
	(t-forall (?me - (move_end h0 p2 p4))
	 (t-exists (?ms - (move_start h0 p2 p4)) (and (= (- ?me ?ms) 20))))	
	(t-forall (?ms - (move_start h0 p2 p5))
	 (t-exists (?me - (move_end h0 p2 p5)) (and (= (- ?me ?ms) 30))))
	(t-forall (?me - (move_end h0 p2 p5))
	 (t-exists (?ms - (move_start h0 p2 p5)) (and (= (- ?me ?ms) 30))))	
	(t-forall (?ms - (move_start h0 p2 p6))
	 (t-exists (?me - (move_end h0 p2 p6)) (and (= (- ?me ?ms) 40))))
	(t-forall (?me - (move_end h0 p2 p6))
	 (t-exists (?ms - (move_start h0 p2 p6)) (and (= (- ?me ?ms) 40))))	
	(t-forall (?ms - (move_start h0 p3 p0))
	 (t-exists (?me - (move_end h0 p3 p0)) (and (= (- ?me ?ms) 30))))
	(t-forall (?me - (move_end h0 p3 p0))
	 (t-exists (?ms - (move_start h0 p3 p0)) (and (= (- ?me ?ms) 30))))	
	(t-forall (?ms - (move_start h0 p3 p1))
	 (t-exists (?me - (move_end h0 p3 p1)) (and (= (- ?me ?ms) 20))))
	(t-forall (?me - (move_end h0 p3 p1))
	 (t-exists (?ms - (move_start h0 p3 p1)) (and (= (- ?me ?ms) 20))))	
	(t-forall (?ms - (move_start h0 p3 p2))
	 (t-exists (?me - (move_end h0 p3 p2)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p3 p2))
	 (t-exists (?ms - (move_start h0 p3 p2)) (and (= (- ?me ?ms) 10))))	
	(t-forall (?ms - (move_start h0 p3 p4))
	 (t-exists (?me - (move_end h0 p3 p4)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p3 p4))
	 (t-exists (?ms - (move_start h0 p3 p4)) (and (= (- ?me ?ms) 10))))	
	(t-forall (?ms - (move_start h0 p3 p5))
	 (t-exists (?me - (move_end h0 p3 p5)) (and (= (- ?me ?ms) 20))))
	(t-forall (?me - (move_end h0 p3 p5))
	 (t-exists (?ms - (move_start h0 p3 p5)) (and (= (- ?me ?ms) 20))))	
	(t-forall (?ms - (move_start h0 p3 p6))
	 (t-exists (?me - (move_end h0 p3 p6)) (and (= (- ?me ?ms) 30))))
	(t-forall (?me - (move_end h0 p3 p6))
	 (t-exists (?ms - (move_start h0 p3 p6)) (and (= (- ?me ?ms) 30))))	
	(t-forall (?ms - (move_start h0 p4 p0))
	 (t-exists (?me - (move_end h0 p4 p0)) (and (= (- ?me ?ms) 40))))
	(t-forall (?me - (move_end h0 p4 p0))
	 (t-exists (?ms - (move_start h0 p4 p0)) (and (= (- ?me ?ms) 40))))	
	(t-forall (?ms - (move_start h0 p4 p1))
	 (t-exists (?me - (move_end h0 p4 p1)) (and (= (- ?me ?ms) 30))))
	(t-forall (?me - (move_end h0 p4 p1))
	 (t-exists (?ms - (move_start h0 p4 p1)) (and (= (- ?me ?ms) 30))))	
	(t-forall (?ms - (move_start h0 p4 p2))
	 (t-exists (?me - (move_end h0 p4 p2)) (and (= (- ?me ?ms) 20))))
	(t-forall (?me - (move_end h0 p4 p2))
	 (t-exists (?ms - (move_start h0 p4 p2)) (and (= (- ?me ?ms) 20))))	
	(t-forall (?ms - (move_start h0 p4 p3))
	 (t-exists (?me - (move_end h0 p4 p3)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p4 p3))
	 (t-exists (?ms - (move_start h0 p4 p3)) (and (= (- ?me ?ms) 10))))	
	(t-forall (?ms - (move_start h0 p4 p5))
	 (t-exists (?me - (move_end h0 p4 p5)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p4 p5))
	 (t-exists (?ms - (move_start h0 p4 p5)) (and (= (- ?me ?ms) 10))))	
	(t-forall (?ms - (move_start h0 p4 p6))
	 (t-exists (?me - (move_end h0 p4 p6)) (and (= (- ?me ?ms) 20))))
	(t-forall (?me - (move_end h0 p4 p6))
	 (t-exists (?ms - (move_start h0 p4 p6)) (and (= (- ?me ?ms) 20))))	
	(t-forall (?ms - (move_start h0 p5 p0))
	 (t-exists (?me - (move_end h0 p5 p0)) (and (= (- ?me ?ms) 50))))
	(t-forall (?me - (move_end h0 p5 p0))
	 (t-exists (?ms - (move_start h0 p5 p0)) (and (= (- ?me ?ms) 50))))	
	(t-forall (?ms - (move_start h0 p5 p1))
	 (t-exists (?me - (move_end h0 p5 p1)) (and (= (- ?me ?ms) 40))))
	(t-forall (?me - (move_end h0 p5 p1))
	 (t-exists (?ms - (move_start h0 p5 p1)) (and (= (- ?me ?ms) 40))))	
	(t-forall (?ms - (move_start h0 p5 p2))
	 (t-exists (?me - (move_end h0 p5 p2)) (and (= (- ?me ?ms) 30))))
	(t-forall (?me - (move_end h0 p5 p2))
	 (t-exists (?ms - (move_start h0 p5 p2)) (and (= (- ?me ?ms) 30))))	
	(t-forall (?ms - (move_start h0 p5 p3))
	 (t-exists (?me - (move_end h0 p5 p3)) (and (= (- ?me ?ms) 20))))
	(t-forall (?me - (move_end h0 p5 p3))
	 (t-exists (?ms - (move_start h0 p5 p3)) (and (= (- ?me ?ms) 20))))	
	(t-forall (?ms - (move_start h0 p5 p4))
	 (t-exists (?me - (move_end h0 p5 p4)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p5 p4))
	 (t-exists (?ms - (move_start h0 p5 p4)) (and (= (- ?me ?ms) 10))))	
	(t-forall (?ms - (move_start h0 p5 p6))
	 (t-exists (?me - (move_end h0 p5 p6)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p5 p6))
	 (t-exists (?ms - (move_start h0 p5 p6)) (and (= (- ?me ?ms) 10))))	
	(t-forall (?ms - (move_start h0 p6 p0))
	 (t-exists (?me - (move_end h0 p6 p0)) (and (= (- ?me ?ms) 60))))
	(t-forall (?me - (move_end h0 p6 p0))
	 (t-exists (?ms - (move_start h0 p6 p0)) (and (= (- ?me ?ms) 60))))	
	(t-forall (?ms - (move_start h0 p6 p1))
	 (t-exists (?me - (move_end h0 p6 p1)) (and (= (- ?me ?ms) 50))))
	(t-forall (?me - (move_end h0 p6 p1))
	 (t-exists (?ms - (move_start h0 p6 p1)) (and (= (- ?me ?ms) 50))))	
	(t-forall (?ms - (move_start h0 p6 p2))
	 (t-exists (?me - (move_end h0 p6 p2)) (and (= (- ?me ?ms) 40))))
	(t-forall (?me - (move_end h0 p6 p2))
	 (t-exists (?ms - (move_start h0 p6 p2)) (and (= (- ?me ?ms) 40))))	
	(t-forall (?ms - (move_start h0 p6 p3))
	 (t-exists (?me - (move_end h0 p6 p3)) (and (= (- ?me ?ms) 30))))
	(t-forall (?me - (move_end h0 p6 p3))
	 (t-exists (?ms - (move_start h0 p6 p3)) (and (= (- ?me ?ms) 30))))	
	(t-forall (?ms - (move_start h0 p6 p4))
	 (t-exists (?me - (move_end h0 p6 p4)) (and (= (- ?me ?ms) 20))))
	(t-forall (?me - (move_end h0 p6 p4))
	 (t-exists (?ms - (move_start h0 p6 p4)) (and (= (- ?me ?ms) 20))))	
	(t-forall (?ms - (move_start h0 p6 p5))
	 (t-exists (?me - (move_end h0 p6 p5)) (and (= (- ?me ?ms) 10))))
	(t-forall (?me - (move_end h0 p6 p5))
	 (t-exists (?ms - (move_start h0 p6 p5)) (and (= (- ?me ?ms) 10))))
        )
    )
)
