DOM="majsp"

[pddl]
lang="pddl"
domain-file="./pddl21/domain.pddl"
problem-file="./pddl21/instances/instance_{PB}.pddl"

[tpp]
lang="tpp"
domain-file="./tpp/domain.pddl"
problem-file="./tpp/instances/instance_{PB}.pddl"
ck-file="./tpp/instances/instance_{PB}_ck.pddl"
