DOM="hsp"

[pddl]
lang="pddl"
domain-file="./pddl21/domain.pddl"
problem-file="./pddl21/instances/instance{PB}.pddl"

[tpp]
lang="tpp"
domain-file="./tpp/domain.pddl"
problem-file="./tpp/instances/instance{PB}.pddl"
ck-file="./tpp/instances/instance{PB}_ck.pddl"

[anml-htn]
lang="anml"
problem-file="./anml/htn/hsp-htn.p{PB}.pb.anml"


[anml-full-htn]
lang="anml"
problem-file="./anml/htn/hsp-htn-full.p{PB}.pb.anml"
